// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: role/role_common.proto

package pb_role

import (
	common "github.com/MamangRust/microservice-payment-gateway-grpc/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIdRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRoleRequest) Reset() {
	*x = FindByIdRoleRequest{}
	mi := &file_role_role_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRoleRequest) ProtoMessage() {}

func (x *FindByIdRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIdRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_role_role_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{1}
}

func (x *RoleResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoleResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponseDeleteAt) Reset() {
	*x = RoleResponseDeleteAt{}
	mi := &file_role_role_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponseDeleteAt) ProtoMessage() {}

func (x *RoleResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*RoleResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{2}
}

func (x *RoleResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RoleResponse          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRole) Reset() {
	*x = ApiResponseRole{}
	mi := &file_role_role_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRole) ProtoMessage() {}

func (x *ApiResponseRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRole.ProtoReflect.Descriptor instead.
func (*ApiResponseRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseRole) GetData() *RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesRole) Reset() {
	*x = ApiResponsesRole{}
	mi := &file_role_role_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesRole) ProtoMessage() {}

func (x *ApiResponsesRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesRole.ProtoReflect.Descriptor instead.
func (*ApiResponsesRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponsesRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesRole) GetData() []*RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseRoleAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleAll) Reset() {
	*x = ApiResponseRoleAll{}
	mi := &file_role_role_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleAll) ProtoMessage() {}

func (x *ApiResponseRoleAll) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleAll.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleAll) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseRoleAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseRoleDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleDelete) Reset() {
	*x = ApiResponseRoleDelete{}
	mi := &file_role_role_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleDelete) ProtoMessage() {}

func (x *ApiResponseRoleDelete) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleDelete) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseRoleDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationRole) Reset() {
	*x = ApiResponsePaginationRole{}
	mi := &file_role_role_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationRole) ProtoMessage() {}

func (x *ApiResponsePaginationRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationRole.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationRole) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponsePaginationRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationRole) GetData() []*RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationRole) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationRoleDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        string                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *common.PaginationMeta  `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationRoleDeleteAt) Reset() {
	*x = ApiResponsePaginationRoleDeleteAt{}
	mi := &file_role_role_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationRoleDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationRoleDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationRoleDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_role_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationRoleDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationRoleDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_role_common_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsePaginationRoleDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationRoleDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationRoleDeleteAt) GetData() []*RoleResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationRoleDeleteAt) GetPagination() *common.PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_role_role_common_proto protoreflect.FileDescriptor

const file_role_role_common_proto_rawDesc = "" +
	"\n" +
	"\x16role/role_common.proto\x12\apb.role\x1a\x10common/api.proto\x1a\x1egoogle/protobuf/wrappers.proto\".\n" +
	"\x13FindByIdRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\"p\n" +
	"\fRoleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"\xb5\x01\n" +
	"\x14RoleResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"n\n" +
	"\x0fApiResponseRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.pb.role.RoleResponseR\x04data\"o\n" +
	"\x10ApiResponsesRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.role.RoleResponseR\x04data\"F\n" +
	"\x12ApiResponseRoleAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseRoleDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb3\x01\n" +
	"\x19ApiResponsePaginationRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.role.RoleResponseR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"pagination\"\xc3\x01\n" +
	"!ApiResponsePaginationRoleDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.role.RoleResponseDeleteAtR\x04data\x129\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x19.pb.common.PaginationMetaR\n" +
	"paginationBIZGgithub.com/MamangRust/microservice-payment-gateway-grpc/pb/role;pb_roleb\x06proto3"

var (
	file_role_role_common_proto_rawDescOnce sync.Once
	file_role_role_common_proto_rawDescData []byte
)

func file_role_role_common_proto_rawDescGZIP() []byte {
	file_role_role_common_proto_rawDescOnce.Do(func() {
		file_role_role_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_role_common_proto_rawDesc), len(file_role_role_common_proto_rawDesc)))
	})
	return file_role_role_common_proto_rawDescData
}

var file_role_role_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_role_role_common_proto_goTypes = []any{
	(*FindByIdRoleRequest)(nil),               // 0: pb.role.FindByIdRoleRequest
	(*RoleResponse)(nil),                      // 1: pb.role.RoleResponse
	(*RoleResponseDeleteAt)(nil),              // 2: pb.role.RoleResponseDeleteAt
	(*ApiResponseRole)(nil),                   // 3: pb.role.ApiResponseRole
	(*ApiResponsesRole)(nil),                  // 4: pb.role.ApiResponsesRole
	(*ApiResponseRoleAll)(nil),                // 5: pb.role.ApiResponseRoleAll
	(*ApiResponseRoleDelete)(nil),             // 6: pb.role.ApiResponseRoleDelete
	(*ApiResponsePaginationRole)(nil),         // 7: pb.role.ApiResponsePaginationRole
	(*ApiResponsePaginationRoleDeleteAt)(nil), // 8: pb.role.ApiResponsePaginationRoleDeleteAt
	(*wrapperspb.StringValue)(nil),            // 9: google.protobuf.StringValue
	(*common.PaginationMeta)(nil),             // 10: pb.common.PaginationMeta
}
var file_role_role_common_proto_depIdxs = []int32{
	9,  // 0: pb.role.RoleResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	1,  // 1: pb.role.ApiResponseRole.data:type_name -> pb.role.RoleResponse
	1,  // 2: pb.role.ApiResponsesRole.data:type_name -> pb.role.RoleResponse
	1,  // 3: pb.role.ApiResponsePaginationRole.data:type_name -> pb.role.RoleResponse
	10, // 4: pb.role.ApiResponsePaginationRole.pagination:type_name -> pb.common.PaginationMeta
	2,  // 5: pb.role.ApiResponsePaginationRoleDeleteAt.data:type_name -> pb.role.RoleResponseDeleteAt
	10, // 6: pb.role.ApiResponsePaginationRoleDeleteAt.pagination:type_name -> pb.common.PaginationMeta
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_role_role_common_proto_init() }
func file_role_role_common_proto_init() {
	if File_role_role_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_role_common_proto_rawDesc), len(file_role_role_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_role_common_proto_goTypes,
		DependencyIndexes: file_role_role_common_proto_depIdxs,
		MessageInfos:      file_role_role_common_proto_msgTypes,
	}.Build()
	File_role_role_common_proto = out.File
	file_role_role_common_proto_goTypes = nil
	file_role_role_common_proto_depIdxs = nil
}
