// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: stats/withdraw/withdraw_stats_amount.proto

package withdraw

import (
	withdraw "github.com/MamangRust/microservice-payment-gateway-grpc/pb/withdraw"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithdrawMonthlyAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawMonthlyAmountResponse) Reset() {
	*x = WithdrawMonthlyAmountResponse{}
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawMonthlyAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawMonthlyAmountResponse) ProtoMessage() {}

func (x *WithdrawMonthlyAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawMonthlyAmountResponse.ProtoReflect.Descriptor instead.
func (*WithdrawMonthlyAmountResponse) Descriptor() ([]byte, []int) {
	return file_stats_withdraw_withdraw_stats_amount_proto_rawDescGZIP(), []int{0}
}

func (x *WithdrawMonthlyAmountResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *WithdrawMonthlyAmountResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type WithdrawYearlyAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawYearlyAmountResponse) Reset() {
	*x = WithdrawYearlyAmountResponse{}
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawYearlyAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawYearlyAmountResponse) ProtoMessage() {}

func (x *WithdrawYearlyAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawYearlyAmountResponse.ProtoReflect.Descriptor instead.
func (*WithdrawYearlyAmountResponse) Descriptor() ([]byte, []int) {
	return file_stats_withdraw_withdraw_stats_amount_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawYearlyAmountResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *WithdrawYearlyAmountResponse) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseWithdrawMonthAmount struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*WithdrawMonthlyAmountResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseWithdrawMonthAmount) Reset() {
	*x = ApiResponseWithdrawMonthAmount{}
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseWithdrawMonthAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseWithdrawMonthAmount) ProtoMessage() {}

func (x *ApiResponseWithdrawMonthAmount) ProtoReflect() protoreflect.Message {
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseWithdrawMonthAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseWithdrawMonthAmount) Descriptor() ([]byte, []int) {
	return file_stats_withdraw_withdraw_stats_amount_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseWithdrawMonthAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseWithdrawMonthAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseWithdrawMonthAmount) GetData() []*WithdrawMonthlyAmountResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseWithdrawYearAmount struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Status        string                          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*WithdrawYearlyAmountResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseWithdrawYearAmount) Reset() {
	*x = ApiResponseWithdrawYearAmount{}
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseWithdrawYearAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseWithdrawYearAmount) ProtoMessage() {}

func (x *ApiResponseWithdrawYearAmount) ProtoReflect() protoreflect.Message {
	mi := &file_stats_withdraw_withdraw_stats_amount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseWithdrawYearAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseWithdrawYearAmount) Descriptor() ([]byte, []int) {
	return file_stats_withdraw_withdraw_stats_amount_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseWithdrawYearAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseWithdrawYearAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseWithdrawYearAmount) GetData() []*WithdrawYearlyAmountResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_stats_withdraw_withdraw_stats_amount_proto protoreflect.FileDescriptor

const file_stats_withdraw_withdraw_stats_amount_proto_rawDesc = "" +
	"\n" +
	"*stats/withdraw/withdraw_stats_amount.proto\x12\x11pb.stats.withdraw\x1a\x17withdraw/withdraw.proto\"X\n" +
	"\x1dWithdrawMonthlyAmountResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\"U\n" +
	"\x1cWithdrawYearlyAmountResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\"\x98\x01\n" +
	"\x1eApiResponseWithdrawMonthAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x04data\x18\x03 \x03(\v20.pb.stats.withdraw.WithdrawMonthlyAmountResponseR\x04data\"\x96\x01\n" +
	"\x1dApiResponseWithdrawYearAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x04data\x18\x03 \x03(\v2/.pb.stats.withdraw.WithdrawYearlyAmountResponseR\x04data2\x81\x04\n" +
	"\x1aWithdrawStatsAmountService\x12p\n" +
	"\x14FindMonthlyWithdraws\x12#.pb.withdraw.FindYearWithdrawStatus\x1a1.pb.stats.withdraw.ApiResponseWithdrawMonthAmount\"\x00\x12n\n" +
	"\x13FindYearlyWithdraws\x12#.pb.withdraw.FindYearWithdrawStatus\x1a0.pb.stats.withdraw.ApiResponseWithdrawYearAmount\"\x00\x12\x80\x01\n" +
	" FindMonthlyWithdrawsByCardNumber\x12'.pb.withdraw.FindYearWithdrawCardNumber\x1a1.pb.stats.withdraw.ApiResponseWithdrawMonthAmount\"\x00\x12~\n" +
	"\x1fFindYearlyWithdrawsByCardNumber\x12'.pb.withdraw.FindYearWithdrawCardNumber\x1a0.pb.stats.withdraw.ApiResponseWithdrawYearAmount\"\x00BKZIgithub.com/MamangRust/microservice-payment-gateway-grpc/pb/stats/withdrawb\x06proto3"

var (
	file_stats_withdraw_withdraw_stats_amount_proto_rawDescOnce sync.Once
	file_stats_withdraw_withdraw_stats_amount_proto_rawDescData []byte
)

func file_stats_withdraw_withdraw_stats_amount_proto_rawDescGZIP() []byte {
	file_stats_withdraw_withdraw_stats_amount_proto_rawDescOnce.Do(func() {
		file_stats_withdraw_withdraw_stats_amount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_withdraw_withdraw_stats_amount_proto_rawDesc), len(file_stats_withdraw_withdraw_stats_amount_proto_rawDesc)))
	})
	return file_stats_withdraw_withdraw_stats_amount_proto_rawDescData
}

var file_stats_withdraw_withdraw_stats_amount_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stats_withdraw_withdraw_stats_amount_proto_goTypes = []any{
	(*WithdrawMonthlyAmountResponse)(nil),       // 0: pb.stats.withdraw.WithdrawMonthlyAmountResponse
	(*WithdrawYearlyAmountResponse)(nil),        // 1: pb.stats.withdraw.WithdrawYearlyAmountResponse
	(*ApiResponseWithdrawMonthAmount)(nil),      // 2: pb.stats.withdraw.ApiResponseWithdrawMonthAmount
	(*ApiResponseWithdrawYearAmount)(nil),       // 3: pb.stats.withdraw.ApiResponseWithdrawYearAmount
	(*withdraw.FindYearWithdrawStatus)(nil),     // 4: pb.withdraw.FindYearWithdrawStatus
	(*withdraw.FindYearWithdrawCardNumber)(nil), // 5: pb.withdraw.FindYearWithdrawCardNumber
}
var file_stats_withdraw_withdraw_stats_amount_proto_depIdxs = []int32{
	0, // 0: pb.stats.withdraw.ApiResponseWithdrawMonthAmount.data:type_name -> pb.stats.withdraw.WithdrawMonthlyAmountResponse
	1, // 1: pb.stats.withdraw.ApiResponseWithdrawYearAmount.data:type_name -> pb.stats.withdraw.WithdrawYearlyAmountResponse
	4, // 2: pb.stats.withdraw.WithdrawStatsAmountService.FindMonthlyWithdraws:input_type -> pb.withdraw.FindYearWithdrawStatus
	4, // 3: pb.stats.withdraw.WithdrawStatsAmountService.FindYearlyWithdraws:input_type -> pb.withdraw.FindYearWithdrawStatus
	5, // 4: pb.stats.withdraw.WithdrawStatsAmountService.FindMonthlyWithdrawsByCardNumber:input_type -> pb.withdraw.FindYearWithdrawCardNumber
	5, // 5: pb.stats.withdraw.WithdrawStatsAmountService.FindYearlyWithdrawsByCardNumber:input_type -> pb.withdraw.FindYearWithdrawCardNumber
	2, // 6: pb.stats.withdraw.WithdrawStatsAmountService.FindMonthlyWithdraws:output_type -> pb.stats.withdraw.ApiResponseWithdrawMonthAmount
	3, // 7: pb.stats.withdraw.WithdrawStatsAmountService.FindYearlyWithdraws:output_type -> pb.stats.withdraw.ApiResponseWithdrawYearAmount
	2, // 8: pb.stats.withdraw.WithdrawStatsAmountService.FindMonthlyWithdrawsByCardNumber:output_type -> pb.stats.withdraw.ApiResponseWithdrawMonthAmount
	3, // 9: pb.stats.withdraw.WithdrawStatsAmountService.FindYearlyWithdrawsByCardNumber:output_type -> pb.stats.withdraw.ApiResponseWithdrawYearAmount
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stats_withdraw_withdraw_stats_amount_proto_init() }
func file_stats_withdraw_withdraw_stats_amount_proto_init() {
	if File_stats_withdraw_withdraw_stats_amount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_withdraw_withdraw_stats_amount_proto_rawDesc), len(file_stats_withdraw_withdraw_stats_amount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_withdraw_withdraw_stats_amount_proto_goTypes,
		DependencyIndexes: file_stats_withdraw_withdraw_stats_amount_proto_depIdxs,
		MessageInfos:      file_stats_withdraw_withdraw_stats_amount_proto_msgTypes,
	}.Build()
	File_stats_withdraw_withdraw_stats_amount_proto = out.File
	file_stats_withdraw_withdraw_stats_amount_proto_goTypes = nil
	file_stats_withdraw_withdraw_stats_amount_proto_depIdxs = nil
}
